name: app
description: Application de gestion du temps compilé avec Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  path_provider:
  shared_preferences: ^0.5.6+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intro_views_flutter: '^2.6.0'
  #flutter_datetime_picker: ^1.3.5
  font_awesome_flutter: ^8.8.1
  google_fonts: ^0.3.10
  #animations: ^1.0.0+5
  flutter_local_notifications: ^1.4.0
  #rxdart: ^0.23.1
  flutter_ringtone_player: ^2.0.0
  #workmanager:
  #foreground_service:
  #background_fetch:
  android_alarm_manager:
  #flutter_isolate: ^1.0.0+11
  intl: ^0.15.8
  url_launcher: ^5.4.2
  flutter_calendar_carousel: ^1.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^0.3.1
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/app_icon.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/intro/concept_gt.jpg
    - assets/images/intro/urgent-important.png
    - assets/images/intro/logo.png
    - assets/images/moi.png
    - assets/images/accueil.png
    - assets/images/acuueil/bleu.jpg
    - assets/images/acuueil/orange.jpg
    - assets/images/acuueil/vert.jpg
    - assets/images/acuueil/violet.jpg
